
spring:
  datasource:
    url: jdbc:mysql://185.99.196.115:3306/order_management
    username: diyetizy
    password: '@Diyet123'
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialization-mode: always
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          time_zone: GMT+3
        dialect: org.hibernate.dialect.MySQL8Dialect
        enable_lazy_load_no_trans: true
  http:
    encoding:
      charset: cp857
      enabled: true
      force: true
server:
  port: 80
